# The location
tel: (352) 123-1234
logo: balance-scale-solid.png
email: sales@services.strikehawk.com
addr: 1720 NW 38TH AVE.\n#57
city: Ocala
state: FL
zip: 34482
country: United States
lat: 29.205120
long: -82.318940
timezone: America/New_York
lang: en-US
